// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeAIUPzmsDSOelAZk6nVKu4vBHBVZzUJE',
    appId: '1:826381084764:web:dae4d884fb4d1b219b1e99',
    messagingSenderId: '826381084764',
    projectId: 'cng-protect',
    authDomain: 'cng-protect.firebaseapp.com',
    databaseURL: 'https://cng-protect-default-rtdb.firebaseio.com',
    storageBucket: 'cng-protect.firebasestorage.app',
    measurementId: 'G-690QBQVKZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVK5F-wcrpVTqCcFdb1hiDSq5xnY4szQY',
    appId: '1:826381084764:android:5cef7995eadc28fe9b1e99',
    messagingSenderId: '826381084764',
    projectId: 'cng-protect',
    databaseURL: 'https://cng-protect-default-rtdb.firebaseio.com',
    storageBucket: 'cng-protect.firebasestorage.app',
  );
}
